### PR TITLE
Add system timing constant for movement during modal presentation.

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Review by ajsecord — COMMENTED** [review]
Don't get me wrong, I love C-based inheritance as much as anyone, but in Objective-C it starts looking a little perverse at times. Is there some reason why these are little data classes so you don't have to do the static initialization and the resulting #define macros?

**Comment by jverkoey** [comment]
Old habits die hard - will happily consider switching to Objective-C classes!

**Comment by jverkoey** [comment]
The original thinking was to minimize memory use, but that's hardly a strong consideration here.

**Comment by ianegordon** [comment]
Is the intention to change this macro into a class?

I typically prefer a static MDMMotionCurve that is defined in the implementation over a macro.

**Review by ianegordon — COMMENTED** [review]
Prefer static over macro?

**Comment by jverkoey** [comment]
I'll have to explore doing so in a follow-up major release. For now we require the macros in order to do static struct initialization.

**Comment by jverkoey** [comment]
Gentle ping.

**Review by ajsecord — APPROVED** [review]
Ok, let's file an issue to track removing the structs and their required #defines.

**Comment by jverkoey** [comment]
Filed #5 to track.

**Pull request merged**
